Танцы с бубном вокруг статикфайлов  №64

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -130,9 +130,15 @@ jobs:
 
       - name: Deploy to server
         run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
           echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
-          docker pull ${{ secrets.DOCKER_USERNAME }}/drf_project:${{ github.sha }}
+          docker pull ${{ secrets.DOCKER_USERNAME }}/drf_project:${{ github.sha }} || {
+            echo "ERROR: Failed to pull image"
+            exit 1
+          }
+#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
+#          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+#          docker pull ${{ secrets.DOCKER_USERNAME }}/drf_project:${{ github.sha }}
           docker stop drf_project || true
           docker rm drf_project || true
           docker system prune -a --volumes --force
