Ладно переводим деплой на Docker-Compose , потому что с DockerHub деплой с некоторыми особенностями

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -119,31 +119,41 @@ jobs:
       - name: Copy .env to server
         run: |
           scp -o StrictHostKeyChecking=no .env ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/tmp/drf_project.env
-  
 
       - name: Deploy to server
         run: |
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
-          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
-          docker pull ${{ secrets.DOCKER_USERNAME }}/drf_project:${{ github.sha }} || {
-            echo "ERROR: Failed to pull image"
-            exit 1
-          }
-          
-          # Удаляем ТОЛЬКО старый контейнер (без очистки образов)
-          docker stop drf_project || true
-          docker rm drf_project || true
-          # Запускаем новый контейнер
-          docker run -d \
-            --name drf_project \
-            --env-file /tmp/drf_project.env \
-            -p 80:8000 \
-            ${{ secrets.DOCKER_USERNAME }}/drf_project:${{ github.sha }}
-          
-          # Ждем 10 секунд, чтобы контейнер успел запуститься
-          sleep 10
-          
-          # Применяем миграции и собираем статику
-          docker exec drf_project python manage.py migrate --noinput
-          docker exec drf_project python manage.py collectstatic --noinput
-          EOF
+          scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/app/
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
+            cd /app && \
+            echo \"${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}\" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \
+            docker compose pull && \
+            docker compose up -d
+          "
+  
+
+#      - name: Deploy to server
+#        run: |
+#          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
+#          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+#          docker pull ${{ secrets.DOCKER_USERNAME }}/drf_project:${{ github.sha }} || {
+#            echo "ERROR: Failed to pull image"
+#            exit 1
+#          }
+#
+#          # Удаляем ТОЛЬКО старый контейнер (без очистки образов)
+#          docker stop drf_project || true
+#          docker rm drf_project || true
+#          # Запускаем новый контейнер
+#          docker run -d \
+#            --name drf_project \
+#            --env-file /tmp/drf_project.env \
+#            -p 80:8000 \
+#            ${{ secrets.DOCKER_USERNAME }}/drf_project:${{ github.sha }}
+#
+#          # Ждем 10 секунд, чтобы контейнер успел запуститься
+#          sleep 10
+#
+#          # Применяем миграции и собираем статику
+#          docker exec drf_project python manage.py migrate --noinput
+#          docker exec drf_project python manage.py collectstatic --noinput
+#          EOF
